sudo: required

services:
  - docker

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - oraclejdk9

before_install:
  - pip2.7 install --user setuptools==24.0.3

install: 
  - pip2.7 install --user cwl-runner cwltool==3.0.20200807132242

script: 
#- cwltool --non-strict Dockstore.cwl test.json 
  - mvn clean install 
  - cwltool --validate Dockstore.cwl
# unable to test tool execution, test data and runtime too large
