sudo: required

services:
  - docker

notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - oraclejdk8

before_install:
  - pip2.7 install --user setuptools==24.0.3

install: 
  - pip2.7 install --user cwl-runner cwltool==1.0.20160712154127 schema-salad==1.14.20160708181155 avro==1.8.1

script: 
#- cwltool --non-strict Dockstore.cwl test.json 
  - mvn clean install 
  - docker built -t quay.io/pancancer/pcawg-sanger-cgp-workflow  . 
# unable to test tool execution, test data and runtime too large
